development: &defaults
  adapter: postgresql
  encoding: unicode
  database: man_development
  pool: 5
  username: enbake
  password: enbake
  host: localhost

test:
  <<: *defaults
  database: man_test

production:
  <<: *defaults
  database: man_prod
